# config_gpu.yaml
workerPoolSpecs:
    machineSpec:
        machineType: n1-standard-8
        acceleratorType: NVIDIA_TESLA_P100 
        acceleratorCount: 1
    replicaCount: 1
    containerSpec:
        imageUri: gcr.io/mlopsdtu2/train.image #possibly needs be gcr.io/mlopsdtu2/docker-images/train.image
        
        
